### ISSUE TITLE
 Cannot read properties of undefined (reading '$toast')

### ISSUE THREAD

**Issue by awalawashington** [MeForma/vue-toaster#31]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$toast')
    at _callee$ (app.js:21711:23)
    at tryCatch (app.js:39729:40)
    at Generator.invoke [as _invoke] (app.js:39960:22)
    at Generator.next (app.js:39785:21)
    at asyncGeneratorStep (app.js:21677:103)
    at _next (app.js:21679:194)

**Comment by nervusdm** [comment]
same here

**Comment by melaniecarr23** [comment]
How about providing your code so you can be helped?  Start with the code in your app.js file, where you're getting the error adding toast.

**Comment by Dekari** [comment]
Cannot make it work

    import Toaster from '@meforma/vue-toaster'


.
.
.
.and then if I use this.$toaster i hit an error...

(option API)
